name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '📝 Documentation'
    labels:
      - 'documentation'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
  default: patch

branches:
  - main
  - dev

template: |
  ## Changes
  $CHANGES

autolabeler:
  - label: "enhancement"
    branch:
      - '/^feat\/.*/'
      
  - label: "bug"
    branch:
      - '/^fix\/.*/'

  - label: "docs"
    branch:
      - '/^docs\/.*/'